contact: null
contributors: null
creators: null
description: Ontology about the gross anatomy of the C. elegans
dosdp_tools_options: --obo-prefixes=true
edit_format: owl
export_formats:
- owl
- obo
- json
github_org: obophenotype
gzip_main: false
id: wbbt
import_group:
  directory: imports/
  disabled: false
  ids: null
  products:
  - description: null
    id: ro
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  rebuild_if_source_changes: true
import_pattern_ontology: false
license: CC-BY
namespaces:
- http://purl.obolibrary.org/obo/WBbt_
obo_format_options: ''
pattern_group: null
pattern_pipelines_group: null
primary_release: full
reasoner: ELK
release_artefacts:
- base
- full
repo: c-elegans-gross-anatomy-ontology
report_fail_on: ERROR
robot_java_args: ''
robot_settings: null
robot_version: null
robotemplate_group: null
subset_group: null
title: C. elegans Gross Anatomy Ontology
travis_emails: null
uribase: http://purl.obolibrary.org/obo
use_dosdps: false
